"""
Enrollment and Payment models.

Enrollment state machine:
  NOT_ENROLLED → PAYMENT_PENDING → ENROLLED → IN_PROGRESS → PASSED → COMPLETED
                                                           → FAILED  → RETAKE_ALLOWED → IN_PROGRESS
  (PAYMENT_FAILED, PAYMENT_CANCELLED are terminal states for a transaction; a new one can be initiated)

A learner may only have ONE enrollment in 'ENROLLED' or 'IN_PROGRESS' status at a time.
Prerequisite enforcement and one-course-at-a-time are both enforced on the backend.
"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import String, Boolean, DateTime, Text, Integer, Float, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base


class Enrollment(Base):
    """
    Tracks a learner's enrollment lifecycle for a single course.

    Status transitions (enforced in the enrollment router):
      payment_pending  — STK push initiated, awaiting M-Pesa callback
      enrolled         — payment confirmed; learner can access all course content
      in_progress      — learner has opened at least one lesson
      passed           — all required quizzes passed; certificate issued
      failed           — final quiz attempt failed; no more retakes allowed
      retake_allowed   — failed, but admin/system grants another attempt
      completed        — passed + certificate downloaded / acknowledged
    """
    __tablename__ = "enrollments"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id:   Mapped[str] = mapped_column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    course_id: Mapped[str] = mapped_column(String, ForeignKey("courses.id", ondelete="CASCADE"), nullable=False, index=True)

    status: Mapped[str] = mapped_column(String(30), nullable=False, default="payment_pending", index=True)
    # payment_pending | enrolled | in_progress | passed | failed | retake_allowed | completed

    # Retake tracking
    attempt_count: Mapped[int] = mapped_column(Integer, default=1)
    max_retakes:   Mapped[int] = mapped_column(Integer, default=3)   # snapshot from course at enrollment time

    # Score / result tracking
    final_score_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    passed:          Mapped[bool | None]  = mapped_column(Boolean, nullable=True)

    # Price paid (snapshot at enrollment time, in KES)
    amount_paid: Mapped[float] = mapped_column(Float, default=0.0)

    enrolled_at:   Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at:  Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at:    Mapped[datetime]        = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at:    Mapped[datetime]        = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    user   = relationship("User")
    course = relationship("Course")
    payments = relationship("MpesaTransaction", back_populates="enrollment", cascade="all, delete-orphan")


class MpesaTransaction(Base):
    """
    Records every M-Pesa STK Push attempt, including the Daraja callback result.

    Security design:
      - Backend initiates the push; phone number is taken from the learner's profile
        or entered on the enrollment form but is NEVER trusted from the callback.
      - The callback is validated using the CheckoutRequestID returned by Daraja
        at initiation time — this prevents spoofed callbacks.
      - Enrollment is activated ONLY when ResultCode == 0 in a validated callback.
      - Duplicate transactions (same CheckoutRequestID) are silently idempotent.
    """
    __tablename__ = "mpesa_transactions"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    enrollment_id: Mapped[str] = mapped_column(String, ForeignKey("enrollments.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id:   Mapped[str] = mapped_column(String, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    course_id: Mapped[str] = mapped_column(String, ForeignKey("courses.id", ondelete="SET NULL"), nullable=True)

    # Daraja-assigned identifiers (never generated by us)
    checkout_request_id:  Mapped[str | None] = mapped_column(String(100), nullable=True, unique=True, index=True)
    merchant_request_id:  Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Payment details confirmed by callback (populated only after successful callback)
    mpesa_receipt_number: Mapped[str | None] = mapped_column(String(50), nullable=True, unique=True)
    phone_number:         Mapped[str | None] = mapped_column(String(20), nullable=True)  # national format
    amount:               Mapped[float]      = mapped_column(Float, default=0.0)

    # Status lifecycle
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    # pending | success | failed | cancelled | timeout | expired

    result_code:        Mapped[int | None]  = mapped_column(Integer, nullable=True)    # 0 = success
    result_description: Mapped[str | None]  = mapped_column(Text, nullable=True)

    initiated_at: Mapped[datetime]        = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    enrollment = relationship("Enrollment", back_populates="payments")
