"""seed/quizzes.py — 5 quizzes (one per course) with mixed question types."""
from sqlalchemy.orm import Session
from app.models.quiz import Quiz, Question
from seed.utils import sid, get_or_none, created, skipped, dt

QUIZZES = [
    dict(id=sid("quiz:fundamentals"), course_id=sid("course:gis-fundamentals"),
         lesson_id=sid("les:fund-m2-l2"), title="GIS Fundamentals Assessment",
         description="Tests core GIS concepts, data types, CRS, and QGIS interface.",
         difficulty="beginner", total_marks=20.0, passing_score_pct=60.0,
         max_attempts=3, time_limit_minutes=20, status="published",
         questions=[
             dict(id=sid("q:fund-mc-1"), type="multiple_choice", marks=2.0,
                  prompt="Which is the BEST description of a Geographic Information System?",
                  options=[{"id":"a","text":"A type of satellite camera"},
                           {"id":"b","text":"A framework for gathering, storing, analysing, and visualising spatially-referenced data"},
                           {"id":"c","text":"A program that creates 3D building models"},
                           {"id":"d","text":"A population statistics database"}],
                  correct_answer="b"),
             dict(id=sid("q:fund-tf-1"), type="true_false", marks=1.0,
                  prompt="A river is most naturally represented as a raster dataset in GIS.",
                  correct_answer=False),
             dict(id=sid("q:fund-mc-2"), type="multiple_choice", marks=2.0,
                  prompt="To calculate exact area of a farm in Makueni County, which CRS should you use?",
                  options=[{"id":"a","text":"WGS 84 (EPSG:4326)"},
                           {"id":"b","text":"WGS 84 / UTM Zone 37S (EPSG:32737)"},
                           {"id":"c","text":"Web Mercator (EPSG:3857)"},
                           {"id":"d","text":"Any CRS works for area calculations"}],
                  correct_answer="b"),
             dict(id=sid("q:fund-fill-1"), type="fill_blank", marks=2.0,
                  prompt="The large central area in QGIS where your map is displayed is called the ___.",
                  correct_answer=["Map Canvas","map canvas","canvas"]),
             dict(id=sid("q:fund-ms-1"), type="multiple_select", marks=3.0, partial_credit=True,
                  prompt="Which of the following are GIS components? (Select all that apply.)",
                  options=[{"id":"a","text":"Hardware"},{"id":"b","text":"Data"},
                           {"id":"c","text":"A paid mapping subscription"},
                           {"id":"d","text":"People"},{"id":"e","text":"Methods"},{"id":"f","text":"A printer"}],
                  correct_answer=["a","b","d","e"]),
             dict(id=sid("q:fund-tf-2"), type="true_false", marks=2.0,
                  prompt="A .qgz file permanently stores all GIS data inside it.",
                  correct_answer=False),
             dict(id=sid("q:fund-sa-1"), type="short_answer", marks=4.0,
                  requires_manual_grading=True,
                  prompt="A public health officer has GPS coordinates of 47 cholera cases and a shapefile of water points. Describe ONE spatial question she could answer by overlaying these two datasets.",
                  correct_answer=None,
                  grading_rubric="2–4 marks for a coherent proximity/spatial question e.g. 'Are cholera cases clustered within 200m of specific water points?'"),
             dict(id=sid("q:fund-fill-2"), type="fill_blank", marks=1.0,
                  prompt="The mathematical framework defining how locations are represented on a flat map is called a ___.",
                  correct_answer=["Coordinate Reference System","CRS","map projection"]),
             dict(id=sid("q:fund-gis-1"), type="gis_workflow", marks=3.0,
                  requires_manual_grading=True,
                  prompt="Describe the step-by-step QGIS workflow to identify all settlements with no water access AND population above 200.",
                  options={"instructions":"Include menu paths and tool names."},
                  correct_answer=None,
                  grading_rubric="3 marks: correct Select by Expression with AND, correct field names, correct operators."),
         ]),
    dict(id=sid("quiz:intermediate"), course_id=sid("course:intermediate-gis"),
         lesson_id=sid("les:int-m1-l2"), title="Intermediate GIS Assessment",
         description="Tests spatial analysis, GEE, and PostGIS knowledge.",
         difficulty="intermediate", total_marks=20.0, passing_score_pct=60.0,
         max_attempts=2, time_limit_minutes=25, status="published",
         questions=[
             dict(id=sid("q:int-mc-1"), type="multiple_choice", marks=2.0,
                  prompt="Which geoprocessing operation creates a zone of specified distance around features?",
                  options=[{"id":"a","text":"Clip"},{"id":"b","text":"Buffer"},
                           {"id":"c","text":"Dissolve"},{"id":"d","text":"Intersect"}],
                  correct_answer="b"),
             dict(id=sid("q:int-tf-1"), type="true_false", marks=1.0,
                  prompt="NDVI values range from -1 to +1, where higher values indicate denser vegetation.",
                  correct_answer=True),
             dict(id=sid("q:int-fill-1"), type="fill_blank", marks=2.0,
                  prompt="The PostGIS function used to calculate distance between two geometries is ___.",
                  correct_answer=["ST_Distance","st_distance"]),
             dict(id=sid("q:int-mc-2"), type="multiple_choice", marks=2.0,
                  prompt="In Google Earth Engine, which method filters an ImageCollection by date?",
                  options=[{"id":"a","text":".filterBounds()"},{"id":"b","text":".sort()"},
                           {"id":"c","text":".filterDate()"},{"id":"d","text":".select()"}],
                  correct_answer="c"),
             dict(id=sid("q:int-ms-1"), type="multiple_select", marks=3.0, partial_credit=True,
                  prompt="Which are valid spatial join predicates in QGIS? (Select all.)",
                  options=[{"id":"a","text":"intersects"},{"id":"b","text":"within"},
                           {"id":"c","text":"nearest"},{"id":"d","text":"dissolves"},{"id":"e","text":"contains"}],
                  correct_answer=["a","b","c","e"]),
             dict(id=sid("q:int-python-1"), type="python_code", marks=4.0,
                  requires_manual_grading=True,
                  prompt="Write a Python function using GeoPandas that takes a GeoDataFrame of points and a buffer distance in metres, and returns buffered polygons in UTM Zone 37S (EPSG:32737).",
                  options={"starter_code":"import geopandas as gpd\n\ndef buffer_points(gdf: gpd.GeoDataFrame, distance_m: float) -> gpd.GeoDataFrame:\n    # Your code here\n    pass\n"},
                  correct_answer=None,
                  grading_rubric="4 marks: correct CRS transform to 32737, correct buffer call, returns GeoDataFrame."),
             dict(id=sid("q:int-sa-1"), type="short_answer", marks=4.0,
                  requires_manual_grading=True,
                  prompt="Explain the difference between supervised and unsupervised land cover classification in satellite imagery analysis.",
                  correct_answer=None,
                  grading_rubric="Supervised: uses training samples with known classes. Unsupervised: algorithm finds natural clusters. 4 marks for accurate distinction with examples."),
             dict(id=sid("q:int-fill-2"), type="fill_blank", marks=2.0,
                  prompt="The PostGIS index type used for spatial queries is called a ___ index.",
                  correct_answer=["GiST","gist","R-tree","rtree"]),
         ]),
    dict(id=sid("quiz:advanced"), course_id=sid("course:advanced-gis"),
         lesson_id=sid("les:adv-m1-l2"), title="Advanced GIS Assessment",
         description="Tests SAR, change detection, Python GIS, and spatial statistics.",
         difficulty="advanced", total_marks=20.0, passing_score_pct=65.0,
         max_attempts=2, time_limit_minutes=30, status="published",
         questions=[
             dict(id=sid("q:adv-mc-1"), type="multiple_choice", marks=2.0,
                  prompt="What is the primary advantage of SAR over optical remote sensing?",
                  options=[{"id":"a","text":"Higher spatial resolution"},
                           {"id":"b","text":"All-weather, day-and-night operation"},
                           {"id":"c","text":"True-colour imagery"},{"id":"d","text":"Free global availability"}],
                  correct_answer="b"),
             dict(id=sid("q:adv-tf-1"), type="true_false", marks=1.0,
                  prompt="Kriging is a deterministic interpolation method using exact distance weighting.",
                  correct_answer=False),
             dict(id=sid("q:adv-fill-1"), type="fill_blank", marks=2.0,
                  prompt="Moran's I statistic measures spatial ___.",
                  correct_answer=["autocorrelation","auto-correlation"]),
             dict(id=sid("q:adv-python-1"), type="python_code", marks=5.0,
                  requires_manual_grading=True,
                  prompt="Write a Python script using Rasterio that opens a GeoTIFF DEM, calculates slope in degrees, and saves the result as a new GeoTIFF.",
                  options={"starter_code":"import rasterio\nimport numpy as np\n\ndef calculate_slope(dem_path: str, output_path: str) -> None:\n    pass\n"},
                  correct_answer=None,
                  grading_rubric="5 marks: correct rasterio.open(), gradient calculation, proper CRS/transform handling, valid output."),
             dict(id=sid("q:adv-r-1"), type="r_code", marks=4.0,
                  requires_manual_grading=True,
                  prompt="Write R code using the terra package to compute zonal statistics (mean NDVI) for administrative districts from an NDVI raster.",
                  options={"starter_code":"library(terra)\n\n# Your code here\n"},
                  correct_answer=None,
                  grading_rubric="4 marks: correct terra::zonal(), appropriate aggregation, readable output."),
             dict(id=sid("q:adv-essay-1"), type="essay", marks=4.0,
                  requires_manual_grading=True,
                  prompt="Critically evaluate Random Forest classification for land cover mapping in Kenya's arid regions. Discuss training data requirements, accuracy assessment, and limitations.",
                  correct_answer=None,
                  grading_rubric="4 marks: structured argument, accurate technical content, examples, critical reflection."),
             dict(id=sid("q:adv-ms-1"), type="multiple_select", marks=2.0, partial_credit=True,
                  prompt="Which Python libraries are commonly used for geospatial analysis? (Select all.)",
                  options=[{"id":"a","text":"GeoPandas"},{"id":"b","text":"Rasterio"},
                           {"id":"c","text":"Matplotlib"},{"id":"d","text":"Shapely"},{"id":"e","text":"Flask"}],
                  correct_answer=["a","b","d"]),
         ]),
    dict(id=sid("quiz:spatial-db"), course_id=sid("course:spatial-databases"),
         lesson_id=sid("les:db-m1-l2"), title="Spatial Databases Assessment",
         description="Tests PostGIS SQL, spatial indexing, and schema design.",
         difficulty="advanced", total_marks=20.0, passing_score_pct=65.0,
         max_attempts=2, time_limit_minutes=30, status="published",
         questions=[
             dict(id=sid("q:db-mc-1"), type="multiple_choice", marks=2.0,
                  prompt="Which PostGIS function returns the bounding box of a geometry?",
                  options=[{"id":"a","text":"ST_Extent"},{"id":"b","text":"ST_Envelope"},
                           {"id":"c","text":"ST_BoundingBox"},{"id":"d","text":"ST_Area"}],
                  correct_answer="b"),
             dict(id=sid("q:db-fill-1"), type="fill_blank", marks=2.0,
                  prompt="The command to add a GiST spatial index on 'geom' in the 'settlements' table starts with: CREATE INDEX ___ ON settlements USING GIST(geom);",
                  correct_answer=["idx_settlements_geom","idx_geom","any_valid_name"]),
             dict(id=sid("q:db-tf-1"), type="true_false", marks=1.0,
                  prompt="ST_DWithin automatically uses a spatial index when one exists.",
                  correct_answer=True),
             dict(id=sid("q:db-sql-1"), type="short_answer", marks=5.0,
                  requires_manual_grading=True,
                  prompt="Write a PostGIS SQL query finding the 3 nearest health clinics to each settlement, returning settlement name, clinic name, and distance in kilometres.",
                  correct_answer=None,
                  grading_rubric="5 marks: ST_Distance with geography cast, CROSS JOIN LATERAL, ORDER BY + LIMIT 3, km conversion."),
             dict(id=sid("q:db-essay-1"), type="essay", marks=6.0,
                  requires_manual_grading=True,
                  prompt="Design a complete PostGIS database schema for a national land registry tracking parcels, ownership history, valuations, and encumbrances.",
                  correct_answer=None,
                  grading_rubric="6 marks: normalised schema, appropriate geometry types, GiST indexes, foreign keys, audit columns."),
             dict(id=sid("q:db-fill-2"), type="fill_blank", marks=2.0,
                  prompt="The pgRouting function for shortest path between two network nodes is ___.",
                  correct_answer=["pgr_dijkstra","pgr_Dijkstra"]),
             dict(id=sid("q:db-ms-1"), type="multiple_select", marks=2.0, partial_credit=True,
                  prompt="Which are valid GeoServer output formats? (Select all.)",
                  options=[{"id":"a","text":"WMS"},{"id":"b","text":"WFS"},
                           {"id":"c","text":"WMTS"},{"id":"d","text":"DXF"},{"id":"e","text":"GML"}],
                  correct_answer=["a","b","c","e"]),
         ]),
    dict(id=sid("quiz:data-science"), course_id=sid("course:spatial-data-science"),
         lesson_id=sid("les:ds-m1-l2"), title="Spatial Data Science Assessment",
         description="Comprehensive assessment of spatial data science skills.",
         difficulty="advanced", total_marks=20.0, passing_score_pct=65.0,
         max_attempts=1, time_limit_minutes=40, status="published",
         questions=[
             dict(id=sid("q:ds-mc-1"), type="multiple_choice", marks=2.0,
                  prompt="Which Python library provides the primary spatial data structure for vector analysis in a pandas-like API?",
                  options=[{"id":"a","text":"Rasterio"},{"id":"b","text":"Fiona"},
                           {"id":"c","text":"GeoPandas"},{"id":"d","text":"Pyproj"}],
                  correct_answer="c"),
             dict(id=sid("q:ds-tf-1"), type="true_false", marks=1.0,
                  prompt="The terra R package replaces the legacy raster package with improved performance.",
                  correct_answer=True),
             dict(id=sid("q:ds-python-1"), type="python_code", marks=6.0,
                  requires_manual_grading=True,
                  prompt="Write a Python script that: (1) loads a CSV of GPS points, (2) converts to GeoDataFrame, (3) reprojects to UTM Zone 37S, (4) computes 1 km buffers, (5) saves as GeoPackage.",
                  options={"starter_code":"import pandas as pd\nimport geopandas as gpd\n\n"},
                  correct_answer=None,
                  grading_rubric="6 marks: 1 each for CSV load, GeoDataFrame, CRS set, reproject, buffer, GeoPackage export."),
             dict(id=sid("q:ds-r-1"), type="r_code", marks=5.0,
                  requires_manual_grading=True,
                  prompt="Using sf and terra, write R code to: load admin boundaries, extract mean NDVI for each, visualise as a choropleth with ggplot2.",
                  options={"starter_code":"library(sf)\nlibrary(terra)\nlibrary(ggplot2)\n\n"},
                  correct_answer=None,
                  grading_rubric="5 marks: sf load, terra extraction, join to sf, ggplot2 choropleth with scale_fill_viridis."),
             dict(id=sid("q:ds-essay-1"), type="essay", marks=4.0,
                  requires_manual_grading=True,
                  prompt="Compare Python (GeoPandas/Rasterio) and R (sf/terra) for geospatial data science workflows, considering performance, ecosystem, visualisation, and use cases.",
                  correct_answer=None,
                  grading_rubric="4 marks: balanced comparison, specific library references, structured argument."),
             dict(id=sid("q:ds-fill-1"), type="fill_blank", marks=2.0,
                  prompt="The spatial statistics measure quantifying similarity of neighbouring values is called Moran's ___.",
                  correct_answer=["I","i"]),
         ]),
]


def seed_quizzes(db: Session, admin_id: str) -> dict:
    quizzes = {}
    for qdef in QUIZZES:
        q = get_or_none(db, Quiz, id=qdef["id"])
        if not q:
            q = Quiz(id=qdef["id"], title=qdef["title"], description=qdef["description"],
                     course_id=qdef["course_id"], lesson_id=qdef.get("lesson_id"),
                     difficulty=qdef["difficulty"], total_marks=qdef["total_marks"],
                     passing_score_pct=qdef["passing_score_pct"], max_attempts=qdef["max_attempts"],
                     time_limit_minutes=qdef["time_limit_minutes"], status=qdef["status"],
                     created_by=admin_id, created_at=dt(5), updated_at=dt(5))
            db.add(q); db.flush()
            created(f"quiz {q.title}")
        else:
            skipped(f"quiz {q.title}")
        quizzes[q.id] = q
        for i, qmeta in enumerate(qdef["questions"]):
            if not get_or_none(db, Question, id=qmeta["id"]):
                db.add(Question(
                    id=qmeta["id"], quiz_id=q.id, type=qmeta["type"],
                    prompt=qmeta["prompt"], options=qmeta.get("options"),
                    correct_answer=qmeta.get("correct_answer"), marks=qmeta["marks"],
                    partial_credit=qmeta.get("partial_credit", False),
                    negative_marking=qmeta.get("negative_marking", 0.0),
                    requires_manual_grading=qmeta.get("requires_manual_grading", False),
                    grading_rubric=qmeta.get("grading_rubric"),
                    order_index=i, created_at=dt(5)))
                db.flush()
    return quizzes
